version: '{build}'

skip_tags: true

environment:
  matrix:
    - ruby_version: "23"
    - ruby_version: "23-x64"

#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  
install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - gem install bundler --no-document -v 1.13.5
  - SET BUNDLE_GEMFILE=Gemfile.norbnacl
  - bundle _1.13.5_ install --retry=3
  - cinst freesshd
  - cinst putty

test_script:
  - SET BUNDLE_GEMFILE=Gemfile.norbnacl
  - SET NET_SSH_RUN_WIN_INTEGRATION_TESTS=YES
  - bundle _1.13.5_ exec rake test

build: off
